### ISSUE TITLE
id属性とclass属性の違いについて

### ISSUE THREAD

**Issue by sice11** [sice11/HTML-CSS_work#1]
第三章
id属性とclass属性の違いについて
なんとなくの理解はできるけれども、
すっきりしない感じ。

[参照](https://jill-tone.com/htmlcss_id_class/)
現在は
id属性：そのファイルで一回しか同じidは使えない
　　　　その性質上、目印？（なんのかはわからない）として利用
class属性：そのファイルで何度でも同じclassを使いまわしできる
　　　　　デザインなど、普段利用するのはこちら
という認識

**Comment by technicakidz** [comment]
ケース：画面中央に `main` のボックスを2つ配置したい
1つであれば 
```
<div id="main"> ~  </div>
```
としてよいが、2つの場合は重複して同じ div要素が存在してしまうので
```
<div class="main" id="main" > ~ </div>
<div class="main" id="sub_main"> ~ </div>
```
として `class` にまとめてしまう。それぞれのスタイルを指定したい可能性があるのでidをそれぞれに振っておくと使いやすくなる。
