### ISSUE TITLE
アクセス権がないため、うまくpushできない？

### ISSUE THREAD

**Issue by sice11** [sice11/HTML-CSS_work#2]
```
fatal: 'branch_cloud9' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
どのようにアクセス権を渡せばいいでしょうか？

**Comment by technicakidz** [comment]
sshkey でアクセス権の設定が必要そうかも。
リポジトリ設定から ssh用の key を発行することができます。
cloud9のセキュリティの面でたしかに恒久的な設定が必要ではあります。
https://qiita.com/GakuNaitou/items/81dbbd3ea6211af71648

**Comment by sice11** [comment]
sshのkeyをプライベート・公開どちらも作成し、
教えていただいたURLを参照に公開キーをGitHubに登録までできました。
ですが、一点疑問点があります。

公開・プライベート作成時に、
[こちら](https://qiita.com/shizuma/items/2b2f873a0034839e47ce)を参考しました。
この手順で作成する際、.sshが作成されるディレクトリが、
gitで作業したいディレクトリではありませんでした。
こちらはこのままでもよいのでしょうか？

GitHubにアクセス許可したいディレクトリは
C:\Users\ユーザー名\Desktop\Git_Work\HTML-CSS_work
実際に.sshが作成されてしまったのは
C:\Users\ユーザー名\.ssh

【懸念点】
実際に作成されてしまった.sshのディレクトリだと、
HTML-CSS_workのディレクトリだけでなく、
今まで作成し、pushまで行ったディレクトリすべてに適応されてしまうのではないか？
という点

**Comment by technicakidz** [comment]
そもそも公開鍵、暗号鍵はどのレポジトリにも必要なため適応されるべきです。
そのため、rootに `.ssh` が配置されることになります。
