### ISSUE TITLE
sshのconfigファイルについて

### ISSUE THREAD

**Issue by sice11** [sice11/HTML-CSS_work#4]
(以前教えていただいたURL)[https://qiita.com/GakuNaitou/items/81dbbd3ea6211af71648]の最後にconfigファイルを作成して、pushする工程があったと思います。

疑問点はconfigファイルは、GitHubにて管理しているファイルに移動させてからpushするという認識でよろしいでしょうか？

現在configファイルは.sshが作成された箇所（C:\Users\PC_User\.ssh）にて作成しており、
GitHubと連携している箇所（①）は別のディレクトリです。

①の箇所にconfigファイルを移動させて、いつも通りpushすればよろしいでしょうか？

**Comment by sice11** [comment]
コンフィグファイルの中身を記載

```
#-------------------
Host github
  HostName github.com
  IdentityFile ~/.ssh/id_rsa
  User git
#-------------------
```

**Comment by sice11** [comment]
.sshのディレクトリ構成
treeコマンドで確認

```
$ pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/| /g'
/c/Users/PC_User/.ssh
|--config
|--id_rsa
|--id_rsa.pub
|--known_hosts
```

treeコマンドがないので、[こちら](https://qiita.com/yone098@github/items/bba8a42de6b06e40983b)のコマンドで代用

**Comment by technicakidz** [comment]
こちらも参考にしてみてください、ユーザに紐付くリポジトリを管理することができます。
https://qiita.com/suthio/items/2760e4cff0e185fe2db9

**Comment by sice11** [comment]
```
$ ssh-keygen -l -f ~/.ssh/id_rsa.pub
3072 SHA256:*************************** PC_User@************ (RSA)
```

確認項目問題なさそうでした。

**Comment by technicakidz** [comment]
`tree` コマンドは以下からダウンロードすると利用できます。
http://gnuwin32.sourceforge.net/packages/tree.htm

**Comment by technicakidz** [comment]
ssh ファイルまわりはやはり問題なさそうなので、github側のsettingsでのsshキー有効状況などもみていきましょう。次回でみていってもいいかもしれません。
